services:
  postgres:
    image: postgres:latest
    container_name: postgresDb
    environment:
      POSTGRES_USER: us
      POSTGRES_PASSWORD: password
      POSTGRES_DB: us
    ports:
      - "5432:5432"
