services:
  postgres:
    image: postgres:latest
    container_name: postgresDb
    environment:
      POSTGRES_USER: us
      POSTGRES_PASSWORD: password
      POSTGRES_DB: us
    ports:
      - "5432:5432"
    volumes:
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres:/data/postgres

volumes:
  postgres:
