spring:
  datasource:
    username: us
    password: password
    url: jdbc:postgresql://localhost:5432/us
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate.order_by.default_null_ordering: last
